export const APTITUDE_CATEGORIES = [
  'All',
  'Quantitative',
  'Data Interpretation',
  'Logical Reasoning',
  'Verbal Ability',
  'Technical'
];

export const APTITUDE_CATEGORY_COLORS = {
  'Quantitative': { bg: '#1a0a3b', text: '#a78bfa', border: '#7c3aed', dot: '#7c3aed' },
  'Data Interpretation': { bg: '#0c1a3b', text: '#60a5fa', border: '#3b82f6', dot: '#3b82f6' },
  'Logical Reasoning': { bg: '#052e16', text: '#4ade80', border: '#22c55e', dot: '#22c55e' },
  'Verbal Ability': { bg: '#3b1a00', text: '#fb923c', border: '#f97316', dot: '#f97316' },
  'Technical': { bg: '#450a0a', text: '#f87171', border: '#ef4444', dot: '#ef4444' },
};

export const APTITUDE_DATA = [
  { id: 'qa-1', category: 'Quantitative', topic: 'Number System', subtopics: 'Prime numbers · Divisibility rules · Remainders · Factors · Trailing zeroes' },
  { id: 'qa-2', category: 'Quantitative', topic: 'HCF & LCM', subtopics: 'Basic concepts · Applications in word problems · Fractions HCF/LCM' },
  { id: 'qa-3', category: 'Quantitative', topic: 'Simplification & Approximation', subtopics: 'BODMAS · Decimal fractions · Square roots & Cube roots' },
  { id: 'qa-4', category: 'Quantitative', topic: 'Fractions & Decimals', subtopics: 'Addition/Subtraction · Comparison · Conversion' },
  { id: 'qa-5', category: 'Quantitative', topic: 'Percentages', subtopics: 'Basic percentage · Successive percentage · Income/Expenditure · Elections' },
  { id: 'qa-6', category: 'Quantitative', topic: 'Profit & Loss', subtopics: 'CP & SP · Markups & Discounts · Dishonest dealer · Successive discounts' },
  { id: 'qa-7', category: 'Quantitative', topic: 'Simple & Compound Interest', subtopics: 'SI vs CI · Difference between SI & CI · Installments' },
  { id: 'qa-8', category: 'Quantitative', topic: 'Ratio & Proportion', subtopics: 'Direct & Inverse proportion · Partnership · Coins · Income/Savings' },
  { id: 'qa-9', category: 'Quantitative', topic: 'Averages', subtopics: 'Basic average · Age problems · Replacement problems · Weighted average' },
  { id: 'qa-10', category: 'Quantitative', topic: 'Mixtures & Alligations', subtopics: 'Rule of Alligation · Repeated replacement · Ratio of mixtures' },
  { id: 'qa-11', category: 'Quantitative', topic: 'Time & Work', subtopics: 'Efficiency · Alternate days · Men-Days-Hours · Leaving/joining work' },
  { id: 'qa-12', category: 'Quantitative', topic: 'Pipes & Cisterns', subtopics: 'Inlet & Outlet · Alternate filling · Leakage problems' },
  { id: 'qa-13', category: 'Quantitative', topic: 'Time, Speed & Distance', subtopics: 'Average speed · Relative speed · Early/Late problems' },
  { id: 'qa-14', category: 'Quantitative', topic: 'Trains', subtopics: 'Crossing poles · Crossing platforms · Crossing other trains' },
  { id: 'qa-15', category: 'Quantitative', topic: 'Boats & Streams', subtopics: 'Upstream · Downstream · Still water speed' },
  { id: 'qa-16', category: 'Quantitative', topic: 'Ages', subtopics: 'Linear equations · Ratio based age problems' },
  { id: 'qa-17', category: 'Quantitative', topic: 'Partnership', subtopics: 'Active/Sleeping partners · Profit distribution based on time & investment' },
  { id: 'qa-18', category: 'Quantitative', topic: 'Mensuration (2D & 3D)', subtopics: 'Area · Perimeter · Volume · Surface Area · Prisms & Pyramids' },
  { id: 'qa-19', category: 'Quantitative', topic: 'Permutations & Combinations', subtopics: 'Arrangements · Selections · Circular permutation · Letters & Digits' },
  { id: 'qa-20', category: 'Quantitative', topic: 'Probability', subtopics: 'Coins · Dice · Cards · Balls · Conditional probability' },
  { id: 'qa-21', category: 'Quantitative', topic: 'Progressions', subtopics: 'Arithmetic Progression (AP) · Geometric Progression (GP) · Harmonic Progression (HP)' },
  { id: 'qa-22', category: 'Quantitative', topic: 'Surds & Indices', subtopics: 'Laws of indices · Rationalization · Comparison of surds' },
  { id: 'qa-23', category: 'Quantitative', topic: 'Logarithms', subtopics: 'Basic properties · Base change theorem' },
  { id: 'qa-24', category: 'Quantitative', topic: 'Clocks & Calendars', subtopics: 'Angle between hands · Faulty clocks · Odd days · Leap years' },
  { id: 'qa-25', category: 'Quantitative', topic: 'Data Sufficiency', subtopics: 'Evaluating statements · Elimination strategy' },

  { id: 'di-1', category: 'Data Interpretation', topic: 'Bar Graphs', subtopics: 'Simple · Grouped · Stacked · Percentage' },
  { id: 'di-2', category: 'Data Interpretation', topic: 'Line Graphs', subtopics: 'Single line · Multi-line · Growth rate calculation' },
  { id: 'di-3', category: 'Data Interpretation', topic: 'Pie Charts', subtopics: 'Degree vs Percentage · Multiple pie charts' },
  { id: 'di-4', category: 'Data Interpretation', topic: 'Tables', subtopics: 'Missing data · Ratio & Percentage calculations' },
  { id: 'di-5', category: 'Data Interpretation', topic: 'Mixed Graphs', subtopics: 'Bar + Pie · Line + Table · Extraction of correlated data' },
  { id: 'di-6', category: 'Data Interpretation', topic: 'Caselets', subtopics: 'Paragraph based DI · Venn diagram based caselets' },

  { id: 'lr-1', category: 'Logical Reasoning', topic: 'Number & Letter Series', subtopics: 'Missing term · Wrong term · Alpha-numeric series' },
  { id: 'lr-2', category: 'Logical Reasoning', topic: 'Analogies', subtopics: 'Word · Number · Letter analogies' },
  { id: 'lr-3', category: 'Logical Reasoning', topic: 'Coding & Decoding', subtopics: 'Letter coding · Number coding · Substitution coding' },
  { id: 'lr-4', category: 'Logical Reasoning', topic: 'Blood Relations', subtopics: 'Family tree · Pointing to a person · Coded relations' },
  { id: 'lr-5', category: 'Logical Reasoning', topic: 'Direction & Distance', subtopics: 'Shadows · Pythagoras theorem · Rotations' },
  { id: 'lr-6', category: 'Logical Reasoning', topic: 'Seating Arrangements', subtopics: 'Linear (North/South) · Circular (Inside/Outside) · Rectangular' },
  { id: 'lr-7', category: 'Logical Reasoning', topic: 'Puzzles', subtopics: 'Floor based · Box based · Scheduling · Attributes' },
  { id: 'lr-8', category: 'Logical Reasoning', topic: 'Syllogisms', subtopics: 'All/Some/None · Possibility cases · Only/Only a few' },
  { id: 'lr-9', category: 'Logical Reasoning', topic: 'Input-Output', subtopics: 'Machine input · Shifting · Mathematical operations' },
  { id: 'lr-10', category: 'Logical Reasoning', topic: 'Order & Ranking', subtopics: 'Left/Right position · Overlapping · Swapping positions' },
  { id: 'lr-11', category: 'Logical Reasoning', topic: 'Inequalities', subtopics: 'Mathematical inequalities · Coded inequalities' },
  { id: 'lr-12', category: 'Logical Reasoning', topic: 'Statements & Conclusions', subtopics: 'Direct conclusion · Probable conclusion' },
  { id: 'lr-13', category: 'Logical Reasoning', topic: 'Statements & Assumptions', subtopics: 'Implicit vs Explicit assumptions' },
  { id: 'lr-14', category: 'Logical Reasoning', topic: 'Cause & Effect', subtopics: 'Independent causes · Common cause · Principal cause' },
  { id: 'lr-15', category: 'Logical Reasoning', topic: 'Course of Action', subtopics: 'Problem solving · Policy implementation' },
  { id: 'lr-16', category: 'Logical Reasoning', topic: 'Critical Reasoning', subtopics: 'Strengthen/Weaken argument · Inference' },
  { id: 'lr-17', category: 'Logical Reasoning', topic: 'Logical Sequence', subtopics: 'Dictionary order · Meaningful sequence' },
  { id: 'lr-18', category: 'Logical Reasoning', topic: 'Venn Diagrams', subtopics: 'Logical representation · intersection · Union' },
  { id: 'lr-19', category: 'Logical Reasoning', topic: 'Clocks & Mirrors', subtopics: 'Mirror image · Water image · Paper folding' },
  { id: 'lr-20', category: 'Logical Reasoning', topic: 'Cubes & Dice', subtopics: 'Painted faces · Unfolded dice · Opposite faces' },

  { id: 'va-1', category: 'Verbal Ability', topic: 'Reading Comprehension', subtopics: 'Main idea · Inference · Tone · Specific details' },
  { id: 'va-2', category: 'Verbal Ability', topic: 'Synonyms & Antonyms', subtopics: 'Contextual meaning · Direct opposites' },
  { id: 'va-3', category: 'Verbal Ability', topic: 'Fill in the Blanks', subtopics: 'Single filler · Double fillers · Grammar based' },
  { id: 'va-4', category: 'Verbal Ability', topic: 'Sentence Correction', subtopics: 'Error spotting · Subject-Verb agreement · Tenses · Prepositions' },
  { id: 'va-5', category: 'Verbal Ability', topic: 'Para Jumbles', subtopics: 'Sentence rearrangement · First/Last sentence fixed' },
  { id: 'va-6', category: 'Verbal Ability', topic: 'Cloze Test', subtopics: 'Passage with blanks · Contextual vocabulary' },
  { id: 'va-7', category: 'Verbal Ability', topic: 'Idioms & Phrases', subtopics: 'Meaning · Usage in sentence' },
  { id: 'va-8', category: 'Verbal Ability', topic: 'One Word Substitution', subtopics: 'Phobias · Ologies · Group terms' },
  { id: 'va-9', category: 'Verbal Ability', topic: 'Active & Passive Voice', subtopics: 'Conversion rules · Exceptional cases' },
  { id: 'va-10', category: 'Verbal Ability', topic: 'Direct & Indirect Speech', subtopics: 'Tense change · Pronoun change · Reporting verbs' },
  { id: 'va-11', category: 'Verbal Ability', topic: 'Vocabulary', subtopics: 'Root words · Prefixes · Suffixes' },
  { id: 'va-12', category: 'Verbal Ability', topic: 'Spellings', subtopics: 'Correctly spelt word · Incorrectly spelt word' },

  { id: 'ta-1', category: 'Technical', topic: 'C / C++ / Java basics', subtopics: 'Pointers · Memory management · JVM internals · Garbage collection · Standard Template Library (STL)' },
  { id: 'ta-2', category: 'Technical', topic: 'Data Structures & Algorithms', subtopics: 'Arrays · Linked Lists · Trees · Graphs · Sorting · Searching · Time/Space complexity' },
  { id: 'ta-3', category: 'Technical', topic: 'DBMS & SQL queries', subtopics: 'Joins · Group By · Normalization · ACID · Indexes · Transactions' },
  { id: 'ta-4', category: 'Technical', topic: 'Operating Systems concepts', subtopics: 'Process vs Thread · Deadlocks · Scheduling algorithms · Virtual memory · Paging' },
  { id: 'ta-5', category: 'Technical', topic: 'Networking basics', subtopics: 'OSI Model · TCP/IP · HTTP/HTTPS · DNS · Routing' },
  { id: 'ta-6', category: 'Technical', topic: 'OOPs concepts', subtopics: 'Inheritance · Polymorphism · Encapsulation · Abstraction · Interfaces vs Abstract classes' },
  { id: 'ta-7', category: 'Technical', topic: 'Pseudocode & Output tracking', subtopics: 'Loop dry run · Recursive function output · Bitwise operations tracking' },
];
